version: '3.1'

services:
  db:
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pipelines
      - POSTGRES_HOST=db
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5


  pipelines:
    build: ./
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    container_name: pipelines
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pipelines
      - POSTGRES_HOST=db
    volumes:
      - ./example_pipeline/original/original.csv:/pipelines/example_pipeline/original/original.csv